server:
 port: 9003
 
spring:
 application:
  name: EMPLOYEE-SERVICE-V2
    
eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
 service-url:
  defaultZone: http://localhost:8761/eureka/
 instance: 
  hostname: localhost